# 1. Heredamos de la imagen de la práctica 2
FROM javi2332/pps_p2_javlluapa:latest

# 2. Solo instalamos GIT (lo único que nos falta en esta capa para bajar OWASP)
RUN apt-get update && apt-get install -y \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 3. Descargamos las Reglas OWASP CRS
# No hace falta configurar ModSecurity de nuevo, ya viene activo de la P2.
RUN git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git /tmp/owasp-crs \
    && mv /tmp/owasp-crs/crs-setup.conf.example /etc/modsecurity/crs-setup.conf \
    && mv /tmp/owasp-crs/rules /etc/modsecurity/rules \
    && rm -rf /tmp/owasp-crs

# 4. Copiamos la configuración específica de esta práctica
# IMPORTANTE: El archivo security2.conf activa las reglas del punto anterior
COPY security2.conf /etc/apache2/mods-available/security2.conf

# NOTA: No hace falta copiar csp_hsts.conf ni hacer hardening, 
# ya lo heredamos de la P1 que está dentro de la P2.

EXPOSE 80 443
CMD ["apache2ctl", "-D", "FOREGROUND"]
