# Ahora hereda de la P4, por lo que ya tiene ModSecurity, OWASP y Evasive
FROM javi2332/pps_p4_javlluapa:latest

# Solo creamos el certificado, el resto ya se hereda
RUN mkdir -p /etc/apache2/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/apache2/ssl/apache.key \
    -out /etc/apache2/ssl/apache.crt \
    -subj "/C=ES/ST=Castellon/L=Castellon/O=Seguridad/CN=www.midominioseguro.com"

COPY default-ssl.conf /etc/apache2/sites-available/default-ssl.conf

RUN a2enmod ssl && \
    a2ensite default-ssl.conf && \
    a2dissite 000-default.conf

EXPOSE 80 443
CMD ["apache2ctl", "-D", "FOREGROUND"]
